# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Restclient < Formula
  desc "A powerful command-line HTTP client for .http and .rest files"
  homepage "https://github.com/ideaspaper/restclient"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ideaspaper/restclient/releases/download/v0.1.3/restclient_darwin_amd64.tar.gz"
      sha256 "ca1e4f759c5c50e2b26219f9f43c276f621aed06f8dfd9bb48cce906afd7938d"

      def install
        bin.install "restclient"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ideaspaper/restclient/releases/download/v0.1.3/restclient_darwin_arm64.tar.gz"
      sha256 "f126981d699c62bf5d1e4a1faa66952f19106f6bcf015201022429bd8382df52"

      def install
        bin.install "restclient"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ideaspaper/restclient/releases/download/v0.1.3/restclient_linux_amd64.tar.gz"
      sha256 "82e7fc58b780ef4e625f182a6bb356ab94cd142803c03fb7ac279525f39849ea"
      def install
        bin.install "restclient"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ideaspaper/restclient/releases/download/v0.1.3/restclient_linux_arm64.tar.gz"
      sha256 "8d37108aedf51fd0175b062bdb9cedb872290f8b723db1b3828984feb7e27bfa"
      def install
        bin.install "restclient"
      end
    end
  end

  test do
    system "#{bin}/restclient", "--version"
  end
end
