# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Restclient < Formula
  desc "A powerful command-line HTTP client for .http and .rest files"
  homepage "https://github.com/ideaspaper/restclient"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ideaspaper/restclient/releases/download/v0.1.1/restclient_darwin_amd64.tar.gz"
      sha256 "9c98cee10137bf209cd96b7af3b6ae2977cdfb88e5818919a048e0b28ad787d3"

      def install
        bin.install "restclient"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ideaspaper/restclient/releases/download/v0.1.1/restclient_darwin_arm64.tar.gz"
      sha256 "c341de6971d0c2bad4b3d445e8e76e405d2da20de6d3846dee726f21735a8edb"

      def install
        bin.install "restclient"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ideaspaper/restclient/releases/download/v0.1.1/restclient_linux_amd64.tar.gz"
      sha256 "49ba652f6204fd1f93555e1770411ed8b827468dc9c9cdf1e25466d04fb2624d"
      def install
        bin.install "restclient"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ideaspaper/restclient/releases/download/v0.1.1/restclient_linux_arm64.tar.gz"
      sha256 "88e5febab951f3f7511ff8b41cd2d278485ceb15c3f585d67bd5cadca558002e"
      def install
        bin.install "restclient"
      end
    end
  end

  test do
    system "#{bin}/restclient", "--version"
  end
end
