# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitnotes" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "9617a54c168a7207850d1d6d7030c2b44a01b5e7f878571d7a88c5ee48a842ac"
      url "https://github.com/ideaspaper/gitnotes/releases/download/v#{version}/gitnotes_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4f411a1f5076cf7b4564e0e8361a9821a73d4f5adc6e78d8b35c92253d2ff86f"
      url "https://github.com/ideaspaper/gitnotes/releases/download/v#{version}/gitnotes_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9ee5a11b9104c4734fdacc17ffd87aa247f06e780de59c1c218a93a3fd32f949"
      url "https://github.com/ideaspaper/gitnotes/releases/download/v#{version}/gitnotes_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3c3c9622ceb7d4500cdcde93feddea070f925b8164265180a3e84785f63a94c4"
      url "https://github.com/ideaspaper/gitnotes/releases/download/v#{version}/gitnotes_linux_arm64.tar.gz"
    end
  end

  name "gitnotes"
  desc "Manage git notes as reviewable, CSV-backed PR/MR comments"
  homepage "https://github.com/ideaspaper/gitnotes"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitnotes"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitnotes"]
    end
  end

  # No zap stanza required

end
