# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitnotes" do
  version "0.1.7"

  on_macos do
    on_intel do
      sha256 "73ea709e319dafdb61d271106126dbf4f517cb0b5c05b057ee1c2f4c8bd163ad"
      url "https://github.com/ideaspaper/gitnotes/releases/download/v#{version}/gitnotes_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0e206253fcf23169047822f49e7c6f33aa8ef4265b3a75c6b06aebdbb11299f5"
      url "https://github.com/ideaspaper/gitnotes/releases/download/v#{version}/gitnotes_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7882fbf656709524f5942b0ef12447c4a8ce2fe87dd67b368c157f70b792c2a6"
      url "https://github.com/ideaspaper/gitnotes/releases/download/v#{version}/gitnotes_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "59187be099fbba5b8cd069b727a0232d61eaacc4c43e408bf64b03ea2c4a3c3a"
      url "https://github.com/ideaspaper/gitnotes/releases/download/v#{version}/gitnotes_linux_arm64.tar.gz"
    end
  end

  name "gitnotes"
  desc "Manage git notes as reviewable, CSV-backed PR/MR comments"
  homepage "https://github.com/ideaspaper/gitnotes"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitnotes"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitnotes"]
    end
  end

  # No zap stanza required

end
