# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitnotes" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "712a5b4a0e609e7a8bcc3d131577c5b8a732d4e1b45c821112ba3d051a3ada22"
      url "https://github.com/ideaspaper/gitnotes/releases/download/v#{version}/gitnotes_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b36955d9b1c89965b4e4f0346948da1cfd8c266c0393bacdebce7b2c56d901cb"
      url "https://github.com/ideaspaper/gitnotes/releases/download/v#{version}/gitnotes_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fbd9cbf4dfd58c9010ee26ee609ff422152766efc2876f8e529da67382c03e5e"
      url "https://github.com/ideaspaper/gitnotes/releases/download/v#{version}/gitnotes_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "85c8d6883ce24fd1d15741d2292acbb6444f29187c7733a627c0f66cdd987221"
      url "https://github.com/ideaspaper/gitnotes/releases/download/v#{version}/gitnotes_linux_arm64.tar.gz"
    end
  end

  name "gitnotes"
  desc "Manage git notes as reviewable, CSV-backed PR/MR comments"
  homepage "https://github.com/ideaspaper/gitnotes"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitnotes"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitnotes"]
    end
  end

  # No zap stanza required

end
