# This file was generated by GoReleaser. DO NOT EDIT.
cask "projector-cli" do
  name "projector-cli"
  desc "A fast and flexible project directory manager for developers"
  homepage "https://github.com/ideaspaper/projector"
  version "0.1.17"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "projector"

  on_macos do
    on_intel do
      url "https://github.com/ideaspaper/projector/releases/download/v#{version}/projector_darwin_amd64.tar.gz"
      sha256 "d6a2877c7deda332fb45101d2c1f2e8ce1ed852043a1058e9077a87c9b234ba4"
    end
    on_arm do
      url "https://github.com/ideaspaper/projector/releases/download/v#{version}/projector_darwin_arm64.tar.gz"
      sha256 "d364bf9ee34f6e6ebfca66bb6a030fc5829a069464ae3dd2a76940d1e45a3e07"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ideaspaper/projector/releases/download/v#{version}/projector_linux_amd64.tar.gz"
      sha256 "d3c44c283e5c430dd5f496736728a31331e61e68fba17438fe1fd0344b1eaa76"
    end
    on_arm do
      url "https://github.com/ideaspaper/projector/releases/download/v#{version}/projector_linux_arm64.tar.gz"
      sha256 "08b89877e195cc96472d90ce8f2eeb7a71ead643d4db643072b0fc0f70af6565"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/projector"]
    end
  end

  # No zap stanza required
end
