# This file was generated by GoReleaser. DO NOT EDIT.
cask "projector-cli" do
  version "0.1.21"

  on_macos do
    on_intel do
      sha256 "e6bd7d8d67483d22b1bc0e0dac03b6e3fcd9e3bbca2e7d8f4b62fb8568ba394e"
      url "https://github.com/ideaspaper/projector/releases/download/v#{version}/projector_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c6f397e5e3457de2078c9d6f6f122bcd82cfd2b10ea5b6132404f9a4662cab1b"
      url "https://github.com/ideaspaper/projector/releases/download/v#{version}/projector_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "95ee609f218abca6f64e3c14c1259dfbcc81d76a4272406e1e8b38411d6c8d34"
      url "https://github.com/ideaspaper/projector/releases/download/v#{version}/projector_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0d1cb3eab16aab1c59c4987b68cfd5a7dfe30ac508ba7fd20fba01f728d7fe80"
      url "https://github.com/ideaspaper/projector/releases/download/v#{version}/projector_linux_arm64.tar.gz"
    end
  end

  name "projector-cli"
  desc "A fast and flexible project directory manager for developers"
  homepage "https://github.com/ideaspaper/projector"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "projector"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/projector"]
    end
  end

  # No zap stanza required

end
