# This file was generated by GoReleaser. DO NOT EDIT.
cask "projector-cli" do
  name "projector-cli"
  desc "A fast and flexible project directory manager for developers"
  homepage "https://github.com/ideaspaper/projector"
  version "0.1.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "projector"

  on_macos do
    on_intel do
      url "https://github.com/ideaspaper/projector/releases/download/v#{version}/projector_darwin_amd64.tar.gz"
      sha256 "6ed83c86f5507c7ca7988d2d826fe5d47eb31e04cecc5da92ee3017dad71cdb0"
    end
    on_arm do
      url "https://github.com/ideaspaper/projector/releases/download/v#{version}/projector_darwin_arm64.tar.gz"
      sha256 "0444bac75c2e4646df5a83b71897f99cda2ac285fdfb16a08bb69b07d8ffd078"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ideaspaper/projector/releases/download/v#{version}/projector_linux_amd64.tar.gz"
      sha256 "792d423b618eef1932680b18cb0e306df3bf7d89899558f566e1434688f5f27d"
    end
    on_arm do
      url "https://github.com/ideaspaper/projector/releases/download/v#{version}/projector_linux_arm64.tar.gz"
      sha256 "8ff266f1c38430c6225b1167480c0edabf5625762f75768bf770363112c94ce4"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/projector"]
    end
  end

  # No zap stanza required
end
