# This file was generated by GoReleaser. DO NOT EDIT.
cask "projector" do
  name "projector"
  desc "A fast and flexible project directory manager for developers"
  homepage "https://github.com/ideaspaper/projector"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "projector"

  on_macos do
    on_intel do
      url "https://github.com/ideaspaper/projector/releases/download/v#{version}/projector_darwin_amd64.tar.gz"
      sha256 "f7f5f767259ce535eef31f8ccf9d037e7f90f46a42ba7e703c99797a0356ba59"
    end
    on_arm do
      url "https://github.com/ideaspaper/projector/releases/download/v#{version}/projector_darwin_arm64.tar.gz"
      sha256 "bca1db86f7ec2e9f4e8d815bb548464c2e7fd917d79472301c6e439a46949713"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ideaspaper/projector/releases/download/v#{version}/projector_linux_amd64.tar.gz"
      sha256 "68540982e9b880bdaac8664ff6e69a555424f613dc363f165cde72731d1f96c8"
    end
    on_arm do
      url "https://github.com/ideaspaper/projector/releases/download/v#{version}/projector_linux_arm64.tar.gz"
      sha256 "1e2a62ce92eff3cde2fed044e8a69b5d2a5db7592d2557bfb691df43df146876"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/projector"]
    end
  end

  # No zap stanza required
end
