# This file was generated by GoReleaser. DO NOT EDIT.
cask "restclient" do
  name "restclient"
  desc "A powerful command-line HTTP client for .http and .rest files"
  homepage "https://github.com/ideaspaper/restclient"
  version "0.2.14"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "restclient"

  on_macos do
    on_intel do
      url "https://github.com/ideaspaper/restclient/releases/download/v#{version}/restclient_darwin_amd64.tar.gz"
      sha256 "f79762190e28a477271abf17b6f2013bd29636443bcd1a1d0d38908af9503801"
    end
    on_arm do
      url "https://github.com/ideaspaper/restclient/releases/download/v#{version}/restclient_darwin_arm64.tar.gz"
      sha256 "5e8eff2e1f57673cf9dc7636db034379dbed503b6bbbc2521944f2107cf31a57"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ideaspaper/restclient/releases/download/v#{version}/restclient_linux_amd64.tar.gz"
      sha256 "ac047fcbdd2062f52244402e6ddf05e4f03a83ae6fbf4088aaf41f9835da8f7d"
    end
    on_arm do
      url "https://github.com/ideaspaper/restclient/releases/download/v#{version}/restclient_linux_arm64.tar.gz"
      sha256 "c24c740e43bfdb79a378f521d6489b6fdd2cf418fbdd72faae695064e5653de5"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/restclient"]
    end
  end

  # No zap stanza required
end
