# This file was generated by GoReleaser. DO NOT EDIT.
cask "restclient" do
  name "restclient"
  desc "A powerful command-line HTTP client for .http and .rest files"
  homepage "https://github.com/ideaspaper/restclient"
  version "0.2.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "restclient"

  on_macos do
    on_intel do
      url "https://github.com/ideaspaper/restclient/releases/download/v#{version}/restclient_darwin_amd64.tar.gz"
      sha256 "3f9390e75f683a0931a25461b5b0bc27742f48efeb2fe6a021449d38d1af6748"
    end
    on_arm do
      url "https://github.com/ideaspaper/restclient/releases/download/v#{version}/restclient_darwin_arm64.tar.gz"
      sha256 "adedd91c8eb15b61b4d7345d7626bbfe5488c5c781a8890fb0500d4f767da545"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ideaspaper/restclient/releases/download/v#{version}/restclient_linux_amd64.tar.gz"
      sha256 "f849f5ab3547ad81df71e941d91a55e143e3ca96dde79dc7a2c4ab6d241a2ee3"
    end
    on_arm do
      url "https://github.com/ideaspaper/restclient/releases/download/v#{version}/restclient_linux_arm64.tar.gz"
      sha256 "182e4f57432f9f5f930b6b35089f5c0c041c0320319dd2f5f504500ff40aee21"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/restclient"]
    end
  end

  # No zap stanza required
end
