# This file was generated by GoReleaser. DO NOT EDIT.
cask "restclient" do
  name "restclient"
  desc "A powerful command-line HTTP client for .http and .rest files"
  homepage "https://github.com/ideaspaper/restclient"
  version "0.1.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "restclient"

  on_macos do
    on_intel do
      url "https://github.com/ideaspaper/restclient/releases/download/v#{version}/restclient_darwin_amd64.tar.gz"
      sha256 "2bf3815ff51b4234a274e8e6af3f2a9f8d26c9aa6056f043d73db6fc7c3c7bfc"
    end
    on_arm do
      url "https://github.com/ideaspaper/restclient/releases/download/v#{version}/restclient_darwin_arm64.tar.gz"
      sha256 "9cb1336fe93651be8da2badff3c3c0ee93d9ec9130c37d546859e5a470216a47"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ideaspaper/restclient/releases/download/v#{version}/restclient_linux_amd64.tar.gz"
      sha256 "732e04c5dd5eced69bc904812d5f6d9ee6dc711de4eb50e8fc4a6a2c32a88f99"
    end
    on_arm do
      url "https://github.com/ideaspaper/restclient/releases/download/v#{version}/restclient_linux_arm64.tar.gz"
      sha256 "3069b85b81070c4668731fc7b2f636949bc0b64a762d20504aba206cb1376a8c"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/restclient"]
    end
  end

  # No zap stanza required
end
