# This file was generated by GoReleaser. DO NOT EDIT.
cask "sheets-mcp" do
  name "sheets-mcp"
  desc "A Model Context Protocol (MCP) server for Google Sheets integration"
  homepage "https://github.com/ideaspaper/sheets-mcp"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sheets-mcp"

  on_macos do
    on_intel do
      url "https://github.com/ideaspaper/sheets-mcp/releases/download/v#{version}/sheets-mcp_darwin_amd64.tar.gz"
      sha256 "a2e3b1feacc01f304ef73fceb8e5494121ba27da825897739a0250d190e659c7"
    end
    on_arm do
      url "https://github.com/ideaspaper/sheets-mcp/releases/download/v#{version}/sheets-mcp_darwin_arm64.tar.gz"
      sha256 "45def6f8b78be3fcae593a0821e31619ba351f7ee069d50bd264572eb8af15ce"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ideaspaper/sheets-mcp/releases/download/v#{version}/sheets-mcp_linux_amd64.tar.gz"
      sha256 "800152ec8ca2fb815eff6e2d7174a74f0f3f4e680c8d8adf1ca998d4193cad4f"
    end
    on_arm do
      url "https://github.com/ideaspaper/sheets-mcp/releases/download/v#{version}/sheets-mcp_linux_arm64.tar.gz"
      sha256 "e0c30ebb912e8fa59d16d2ce5e2d8a75ed2fdb674703cae6061b6bb826ec3620"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sheets-mcp"]
    end
  end

  # No zap stanza required
end
