# This file was generated by GoReleaser. DO NOT EDIT.
cask "sheets-mcp" do
  name "sheets-mcp"
  desc "A Model Context Protocol (MCP) server for Google Sheets integration"
  homepage "https://github.com/ideaspaper/sheets-mcp"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sheets-mcp"

  on_macos do
    on_intel do
      url "https://github.com/ideaspaper/sheets-mcp/releases/download/v#{version}/sheets-mcp_darwin_amd64.tar.gz"
      sha256 "eead6da048471c1d5504fd4d9feb65cbb0df9b85c522155423a476ac0e3e5802"
    end
    on_arm do
      url "https://github.com/ideaspaper/sheets-mcp/releases/download/v#{version}/sheets-mcp_darwin_arm64.tar.gz"
      sha256 "bf979d2a7bc7b1b6e7824e60f7737a1163ec4a95ee7358c1ba25f21333e252d7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ideaspaper/sheets-mcp/releases/download/v#{version}/sheets-mcp_linux_amd64.tar.gz"
      sha256 "244b0006e3f3d9302acbd96d97996435606b4461ebb69d3a25f12c1a4e41bec3"
    end
    on_arm do
      url "https://github.com/ideaspaper/sheets-mcp/releases/download/v#{version}/sheets-mcp_linux_arm64.tar.gz"
      sha256 "e805f6437775134cf3d24f1945f0a80a99165d106df61c201539034b0364b3d7"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sheets-mcp"
    end
  end

  # No zap stanza required
end
