# This file was generated by GoReleaser. DO NOT EDIT.
cask "sheets-mcp" do
  name "sheets-mcp"
  desc "A Model Context Protocol (MCP) server for Google Sheets integration"
  homepage "https://github.com/ideaspaper/sheets-mcp"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sheets-mcp"

  on_macos do
    on_intel do
      url "https://github.com/ideaspaper/sheets-mcp/releases/download/v#{version}/sheets-mcp_darwin_amd64.tar.gz"
      sha256 "ab2765faf80e1d86211e6e3273a873c98e3e958bce5bdccdc174d4dfcb0ef989"
    end
    on_arm do
      url "https://github.com/ideaspaper/sheets-mcp/releases/download/v#{version}/sheets-mcp_darwin_arm64.tar.gz"
      sha256 "1110a4857524c8f7343b14d59e6346c1d8e79e5f58dd04076e3fd8e56bd5b112"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ideaspaper/sheets-mcp/releases/download/v#{version}/sheets-mcp_linux_amd64.tar.gz"
      sha256 "24aa2d5b704a509f1ec27d918ced81d7c557436ddbc954bd605fd5c8b035f063"
    end
    on_arm do
      url "https://github.com/ideaspaper/sheets-mcp/releases/download/v#{version}/sheets-mcp_linux_arm64.tar.gz"
      sha256 "f44fe55433eaa19c3215d2fb33a3443cd2bb34a36a9dfbfa980d8fd525825158"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sheets-mcp"
    end
  end

  # No zap stanza required
end
